version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: nexushire-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: nexushire-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: nexushire-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data: