module.exports={
    apps:[
        {
            name:"nexushire-backend",
            script:"dist/server.js",
            instances:"max",
            exec_mode:"cluster",
            env:{
                NODE_ENV:"production",
            },
        },
    ],
};